language: python
python:
	- 2.7

# Command to install dependencies
install: pip -q install cx_Freeze

# Commands to build, test and clean with `make`
before_script: make
script: make test
after_script: make clean
