#
# Appveyor CI configuration.
#

environment:
    matrix:
        - PYTHON: "C:/Python27"

install:
    - "ECHO %PATH%"
    # Download Python package manager (`pip`):
    - ps: (new-object net.webclient).DownloadFile("http://raw.github.com/pypa/pip/master/contrib/get-pip.py", "C:/get-pip.py")
    - "%PYTHON%/python.exe C:/get-pip.py"

    # Install cxfreeze utility via pip:
    - "%PYTHON%/Scripts/pip.exe -q install cx_Freeze"

    # Download txtrevise utility, a depedency of packager:
    - ps: (new-object net.webclient).DownloadFile("https://raw.githubusercontent.com/stpettersens/txtrevise/master/python/txtrevise.py", "C:/txtrevise.py")

build_script:
    - "%PYTHON%/python.exe %PYTHON%/Scripts/cxfreeze C:/txtrevise.py --target-dir ."
    - ps: "mv txtrevise.exe C:/"
    - ps: "rm bz2.pyd"
    - ps: "rm unicodedata.pyd"
    - ps: "rm python27.dll"
    - "%PYTHON%/python.exe %PYTHON%/Scripts/cxfreeze packager.py --target-dir ."

test_script:
    - "packager.exe -p io.stpettersen.example.helloworld -m HelloWorld -cp . -r examples -v"
    - "java.exe -jar HelloWorld.jar"

on_success:
    - ps: "rm C:/txtrevise.exe"
    - ps: "rm packager.exe"
